networks:
    app:

services:
    database:
        image: "mysql:8.2"
        restart: "no"
        healthcheck:
            test: [ "CMD-SHELL", "mysql -h localhost -u struktal -pstruktal -e 'SELECT 1' struktal" ]
            interval: 5s
            timeout: 3s
            retries: 10
        environment:
            TZ: "UTC"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "struktal"
            MYSQL_USER: "struktal"
            MYSQL_PASSWORD: "struktal"
        ports:
            - "3306:3306"
        networks:
            - "app"

    app:
        image: "struktaltest"
        restart: "no"
        depends_on:
            database:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "nc -z localhost 80 || exit 1" ]
            interval: 5s
            timeout: 3s
            retries: 10
        environment:
            TZ: "UTC"
        volumes:
            - "./config:/app/config"
        ports:
            - "3000:80"
        networks:
            - "app"
