FROM alpine:latest

# Update package manager
RUN apk update && apk upgrade
RUN apk --no-cache add tzdata

# Install nginx and PHP
RUN apk --no-cache add nginx php83 php83-fpm composer git

# Install PHP packages
RUN apk --no-cache add php-session php-tokenizer php-mysqli php-pdo php-pdo_mysql php-curl php-gd php-intl php-mbstring php-xml php-simplexml php-ctype php-apcu

# Copy application files
COPY --chown=nginx:nginx . /app
COPY ./docker/nginx-config /etc/nginx
COPY ./docker/php-fpm-config /etc/php83/php-fpm.d
COPY ./docker/entrypoint-dev.sh /app

# Adjust permissions
RUN mkdir -p /app/logs && \
    mkdir -p /app/files && \
    mkdir -p /app/template-cache && \
    chown -R nginx:nginx /app/logs && \
    chown -R nginx:nginx /app/files && \
    chown -R nginx:nginx /app/template-cache && \
    chmod 777 /app/logs && \
    chmod 777 /app/files && \
    chmod 777 /app/template-cache && \
    chmod +x /app/entrypoint-dev.sh

# Setup crontab
RUN crontab -u nginx /app/src/cronjobs/.crontab

# Build the application
RUN cd /app && composer build

EXPOSE 80
ENTRYPOINT ["/app/entrypoint-dev.sh"]
