name: Build and deploy image to GHCR

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get lowercase repository details
        id: lowercase-repo-details
        shell: pwsh
        run: |
          "::set-output name=repo::$($env:GITHUB_REPOSITORY.ToLowerInvariant())"

      - name: Build and deploy image
        run: |
          docker build -t ghcr.io/${{ steps.lowercase-repo-details.outputs.repo }}:latest .
          docker push ghcr.io/${{ steps.lowercase-repo-details.outputs.repo }}:latest
