on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: AutoDeploy
        run: |
          if [ "${{vars.AUTODEPLOY_ACTIVATED}}" != "true" ]; then
            echo "Cancelled deployment because ${{vars.AUTODEPLOY_ACTIVATED}} is not set or not true"
            exit 0
          fi
          
          echo "Calling ${{vars.AUTODEPLOY_BASE_URL}}/deploy"
          RESPONSE=$(curl -s -w "\\n%{http_code}" -u ${{secrets.AUTODEPLOY_AUTH_USERNAME}}:${{secrets.AUTODEPLOY_AUTH_PASSWORD}} ${{vars.AUTODEPLOY_BASE_URL}}/deploy)
          HTTP_CODE=$(echo "${RESPONSE}" | tail -n 1)
          HTTP_BODY=$(echo "${RESPONSE}" | head -n -1)
          echo "${HTTP_BODY}"
          
          if [[ "$HTTP_CODE" == "200" ]]; then
            exit 1
          fi
